### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by EnricoMonese** [RomuloSan/UIFramework4Unity#2]
I was doing some changes to use this in my game. Wanted to ask before doing a pr.
I removed the fading functionality, but added more events. And removed canvases from menus  prefabs. I used only one canvas on the MenuManager. This gives better performance and also scales much better when having many menus. This and the removed fading allow for much more freedom for the user and cleaner code. The added events still allow for customization, such as fading or custom animations, to be added if wanted.
Also added some preprocessor tags to exclude editor code from builds.
If you are interested in this changes I can fix it up a bit and submit a pr. 👍

**Comment by RomuloSan** [comment]
Hello Enrico, feel free to make improvements. Your ideas look great and I'm willing to help you improve this tool.

**Comment by EnricoMonese** [comment]
I'll clean it up a bit and submit a pr then 👌
