### ISSUE TITLE
Creating on start breaks menus

### ISSUE THREAD

**Issue by EnricoMonese** [RomuloSan/UIFramework4Unity#4]
> NullReferenceException: Object reference not set to an instance of an object
> UIFramework.MenuManager+Transition.AddListener (UIFramework.MenuManager m) (at Assets/UIFramework/UIFramework/MenuManager.cs:41)
> UIFramework.MenuManager.Init () (at Assets/UIFramework/UIFramework/MenuManager.cs:116)
> UIFramework.MenuManager.CreateMenu () (at Assets/UIFramework/UIFramework/MenuManager.cs:97)
> UIFramework.MenuManagerEditor.OnInspectorGUI () (at Assets/UIFramework/UIFramework/Editor/MenuManagerEditor.cs:25)
> UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor[] editors, Int32 editorIndex, Boolean rebuildOptimizedGUIBlock, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1227)
> UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by RomuloSan** [comment]
Fixed up in the last [commit](https://github.com/RomuloSan/UIFramework4Unity/commit/d22fd3c6bca17d82e2f65fbe60685c4e5cc51657)
