### ISSUE TITLE
[IDEA] Add Menu Prefabs list in node editor

### ISSUE THREAD

**Issue by EnricoMonese** [RomuloSan/UIFramework4Unity#6]
Add a thing like this also in the node editor
![schermata 2017-05-28 alle 17 57 44](https://cloud.githubusercontent.com/assets/19847464/26530142/3e1009ca-43cf-11e7-8693-79ad259ecc20.png)

Maybe even remove it from the inspector. Leave in the inspector only a button to open the editor. And move the <kbd>Create New</kbd> button to the node editor too.

**Comment by RomuloSan** [comment]
Done in new [commit](https://github.com/RomuloSan/UIFramework4Unity/commit/be7405b2340fbd7f24903f27ec6cc61c1f6307c5)
The <kbd>create new</kbd> button is now <kbd>Remove All Nodes</kbd> on context menu

![alt text](http://i.imgur.com/Vr7XF4T.png)
